import type { AirtableRecord } from '../components/admin/types';

export function getDevMockOrders(): AirtableRecord[] {
  const today = new Date().toISOString().slice(0, 10);
  const yesterday = new Date(Date.now() - 86400000).toISOString().slice(0, 10);
  const twoDaysAgo = new Date(Date.now() - 2 * 86400000).toISOString().slice(0, 10);
  const fourDaysAgo = new Date(Date.now() - 4 * 86400000).toISOString().slice(0, 10);
  const sevenDaysAgo = new Date(Date.now() - 7 * 86400000).toISOString().slice(0, 10);

  return [
    {
      id: 'rec_live_001',
      fields: {
        orderID: '10842',
        Created: today,
        Name: 'Vikramaditya Sharma',
        Phone: '9845123984',
        Email: 'vikram.sharma@gmail.com',
        Address: 'Flat 402, Prestige Tower, Indiranagar 100ft Road, Bengaluru, Karnataka 560038',
        City: 'Bengaluru',
        State: 'Karnataka',
        Pincode: '560038',
        Items: 'Retra 5mg (Retatrutide) x 2, Bacteriostatic Water 10ml x 1',
        'Total (₹)': 11800,
        Payment: 'UPI / Prepaid',
        'Payment Status': 'VERIFIED',
        Status: 'Paid',
        Delivery: 'Standard Free (3-5 days)',
        Transaction: 'UPI-9823472091',
      },
    },
    {
      id: 'rec_live_002',
      fields: {
        orderID: '10843',
        Created: today,
        Name: 'Dr. Ananya Roy',
        Phone: '9820491823',
        Email: 'ananya.roy@kem.edu',
        Address: 'Room 12, Senior Resident Hostel, KEM Hospital Campus, Parel, Mumbai, Maharashtra 400012',
        City: 'Mumbai',
        State: 'Maharashtra',
        Pincode: '400012',
        Items: 'GHK-Cu 50mg x 1, BPC-157 10mg x 1',
        'Total (₹)': 8400,
        Payment: 'UPI / Prepaid',
        'Payment Status': 'VERIFIED',
        Status: 'New',
        Delivery: 'Express Delivery (24-48h)',
        Transaction: 'UPI-5529103948',
      },
    },
    {
      id: 'rec_live_003',
      fields: {
        orderID: '10844',
        Created: today,
        Name: 'Rohit Khandelwal',
        Phone: '9711209384',
        Email: 'rohit.k@fintech.in',
        Address: 'B-14, Ground Floor, Sector 44, Near Golf Course, Gurugram, Haryana 122003',
        City: 'Gurugram',
        State: 'Haryana',
        Pincode: '122003',
        Items: 'Tirzepatide 10mg x 1',
        'Total (₹)': 6900,
        Payment: 'Cash on Delivery (COD)',
        'Payment Status': 'PENDING',
        Status: 'Confirmed',
        Delivery: 'Standard Free (3-5 days)',
      },
    },
    {
      id: 'rec_live_004',
      fields: {
        orderID: '10839',
        Created: yesterday,
        Name: 'Siddharth Iyer',
        Phone: '9448102934',
        Email: 'sid.iyer@cognizant.com',
        Address: 'Plot 88, 3rd Main, Anna Nagar West, Chennai, Tamil Nadu 600040',
        City: 'Chennai',
        State: 'Tamil Nadu',
        Pincode: '600040',
        Items: 'Retra 10mg (Retatrutide) x 1',
        'Total (₹)': 9800,
        Payment: 'UPI / Prepaid',
        'Payment Status': 'VERIFIED',
        Status: 'Shipped',
        Delivery: 'Express Delivery (24-48h)',
        'AWB Number': 'DELH-892349102',
        'Tracking ID': 'TRK-9823412',
        Courier: 'Delhivery Surface',
      },
    },
    {
      id: 'rec_live_005',
      fields: {
        orderID: '10838',
        Created: yesterday,
        Name: 'Kavita Menon',
        Phone: '9880192847',
        Email: 'kavita.m@gmail.com',
        Address: '14/2, Panampilly Nagar, Near Avenue Centre, Kochi, Kerala 682036',
        City: 'Kochi',
        State: 'Kerala',
        Pincode: '682036',
        Items: 'BPC-157 10mg x 2',
        'Total (₹)': 7600,
        Payment: 'UPI / Prepaid',
        'Payment Status': 'VERIFIED',
        Status: 'Delivered',
        Delivery: 'Standard Free (3-5 days)',
        'AWB Number': 'BLUEDART-592819',
        'Tracking ID': 'BD-5928190',
        Courier: 'BlueDart Express',
      },
    },
    {
      id: 'rec_live_006',
      fields: {
        orderID: '10830',
        Created: twoDaysAgo,
        Name: 'Aditya Deshmukh',
        Phone: '9867019283',
        Email: 'aditya.deshmukh@tcs.com',
        Address: 'Flat 503, Clover Highlands, NIBM Road, Kondhwa, Pune, Maharashtra 411048',
        City: 'Pune',
        State: 'Maharashtra',
        Pincode: '411048',
        Items: 'Retra 5mg x 1, GHK-Cu 50mg x 1',
        'Total (₹)': 10200,
        Payment: 'Cash on Delivery (COD)',
        'Payment Status': 'PENDING',
        Status: 'Shipped',
        Delivery: 'Standard Free (3-5 days)',
        'AWB Number': 'XPRSS-2918239',
        'Tracking ID': 'XPRS-98129',
        Courier: 'XpressBees',
      },
    },
    {
      id: 'rec_live_007',
      fields: {
        orderID: '10821',
        Created: fourDaysAgo,
        Name: 'Meera Nambiar',
        Phone: '9740192834',
        Email: 'meera.nambiar@wipro.com',
        Address: 'Villa 12, Palm Meadows, Whitefield, Bengaluru, Karnataka 560066',
        City: 'Bengaluru',
        State: 'Karnataka',
        Pincode: '560066',
        Items: 'Retra 10mg x 2',
        'Total (₹)': 19600,
        Payment: 'UPI / Prepaid',
        'Payment Status': 'VERIFIED',
        Status: 'Delivered',
        Delivery: 'Express Delivery (24-48h)',
      },
    },
    {
      id: 'rec_live_008',
      fields: {
        orderID: '10815',
        Created: sevenDaysAgo,
        Name: 'Arjun Singhania',
        Phone: '9819028374',
        Email: 'arjun@singhania-law.in',
        Address: 'B-201, Defence Colony, Flyover Market Road, New Delhi, Delhi 110024',
        City: 'New Delhi',
        State: 'Delhi',
        Pincode: '110024',
        Items: 'GHK-Cu 50mg x 2',
        'Total (₹)': 9200,
        Payment: 'UPI / Prepaid',
        'Payment Status': 'VERIFIED',
        Status: 'Delivered',
        Delivery: 'Standard Free (3-5 days)',
      },
    },

    // ── Intentional Junk / Bunk / Duplicate Test Orders ──────────────────────
    {
      id: 'rec_junk_dup_001',
      fields: {
        orderID: '10845',
        Created: today,
        Name: 'Vikramaditya Sharma',
        Phone: '9845123984', // Same phone as rec_live_001
        Email: 'vikram.sharma@gmail.com',
        Address: 'Flat 402, Prestige Tower, Indiranagar 100ft Road, Bengaluru, Karnataka 560038',
        Items: 'Retra 5mg (Retatrutide) x 2, Bacteriostatic Water 10ml x 1',
        'Total (₹)': 11800,
        Payment: 'UPI / Prepaid',
        'Payment Status': 'UNPAID',
        Status: 'New',
        Delivery: 'Standard Free (3-5 days)',
      },
    },
    {
      id: 'rec_junk_phone_002',
      fields: {
        orderID: '10846',
        Created: today,
        Name: 'Rahul Verma',
        Phone: '1234567890', // Sequential dummy number
        Email: 'rahul.test@tempmail.com',
        Address: 'House 12, MG Road, Pune, Maharashtra 411001',
        Items: 'Retra 5mg x 1',
        'Total (₹)': 5900,
        Payment: 'Cash on Delivery (COD)',
        Status: 'New',
      },
    },
    {
      id: 'rec_junk_addr_003',
      fields: {
        orderID: '10847',
        Created: yesterday,
        Name: 'Suresh Kumar',
        Phone: '9821982198', // Low entropy repeat number
        Address: 'asdfghjk qwerty test address na na none', // Gibberish / fake address
        Items: 'BPC-157 10mg x 1',
        'Total (₹)': 3800,
        Payment: 'Cash on Delivery (COD)',
        Status: 'New',
      },
    },
    {
      id: 'rec_junk_name_004',
      fields: {
        orderID: '10848',
        Created: yesterday,
        Name: 'test test', // Dummy test name
        Phone: '9999999999', // All repeated digits
        Address: 'test flat 101, test street, test city 110001',
        Items: 'GHK-Cu 50mg x 1',
        'Total (₹)': 4600,
        Payment: 'Cash on Delivery (COD)',
        Status: 'New',
      },
    },
    {
      id: 'rec_junk_zero_005',
      fields: {
        orderID: '10849',
        Created: twoDaysAgo,
        Name: 'Dummy User',
        Phone: '8888888888',
        Address: 'Sample test building, Sector 1, Noida, Uttar Pradesh 201301',
        Items: 'Test Product Sample',
        'Total (₹)': 1, // ₹1 dummy order
        Payment: 'Cash on Delivery (COD)',
        Status: 'New',
      },
    },
  ];
}
